[package]
name = "rustyfi"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustyfi"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
idl-build = ["anchor-lang/idl-build"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl  = { version = "0.30.1", features = ["token"] }
